import requests
import base64
import struct

from pwn import xor
from Crypto.Util.number import bytes_to_long

# https://toadstyle.org/cryptopals/63.txt
# So GCM mac uses the Associated Data and Ciphertext as well as some L and C to calculate the mac
#  AD*y^3 + C*y^2 + L*y + S
# Then you can just plug in the mask for y and evaluate it to get the MAC
# AD and C are known, so the only thing we don't know is the mask
# This is generated using just the key and nonce. Repeated nonce = repeated MAC mask 
# 
# It's GF(2^128) for the polynomial. Because it's GF(2^x), it represents everything as polynomials
#   with a coefficient in GF(2)
# Addition and subtraction are both XOR
# Multiplication and division are trickier... 
# 
# The modulus for GF(2^128) is x^128 + x^7 + x^2 + x + 1 
# The auth key (h) is generated by E(K, 0) and gets converted into a field element
#   You then zero-pad the elements of auth data to BS as well as the ciphertext, all appended
#   Then you add a last block with the bit length length of each (original, not padded)
#   a0 || a1 || c0 || c1 || c2 || len(AD) || len(C)
# Then for each block of that chain of blocks, you do g += b, then g += h (in the field, ofc)
# Then for the final tag, you do g + E(K, nonce || 1) and that's it
# 
# When we rethink this process, we can write it as:
#   t = (((((((((((h * a0) + a1) * h) + c0) * h) + c1) * h) + c2) * h) + len) * h) + s
#   t = a0*h^6 + a1*h^5 + c0*h^4 + c1*h^3 + c2*h^2 + len*h + s
# 
# SO we can reconstruct the MAC by re-constructing that polynomial with the auth data 
#   the writeup suggests that you add two together, which will give you a polynomial WITHOUT s,
#   from which you can factor the h value, which only depends on the key
# 
#     t0 = a0*h^6 + a1*h^5 + c0*h^4 + c1*h^3 + c2*h^2 + l0*h + s
#     t1 =                   b0*h^4 + d0*h^3 + d1*h^2 + l1*h + s
#     t0 + t1 = a0*h^6 + a1*h^5 + (c0 + b0)*h^4 + (c1 + d0)*h^3 +
#               (c2 + d1)*h^2 + (l0 + l1)*h
#     0 = a0*h^6 + a1*h^5 + (c0 + b0)*h^4 + (c1 + d0)*h^3 +
#         (c2 + d1)*h^2 + (l0 + l1)*h + (t0 + t1)
#     f(y) = a0*y^6 + a1*y^5 + (c0 + b0)*y^4 + (c1 + d0)*y^3 +
#            (c2 + d1)*y^2 + (l0 + l1)*y + (t0 + t1)
#
#   And using this you know that f(h) = 0, which makes it factorable... crazy
# 
# Factoring a polynomial isn't tooooo bad. And there are algoritms (and a sagemath function) for it out there
# 0. Make the polynomial monic (meaning a leading coeficcient of 1)
# 1. Perform a square-free factorization. Just find any doubled factors and pull them out
# 2. Then you take the square-free polynomials and find its distinct-degree factorization, meaning separating 
#   out polynomials that are products of smaller polynomials of equal degree
# 3. Finally, we take each factor from before and perform and equal-dregree factorization (gathering smaller 
#   products of equal degrees)
# Cantor-Zassenhaus is a great algorithm that does this
# 
# If you find a first-degree factor of it (y + c), the authentication key is c #

# Some utility functions pulled from: https://meowmeowxw.gitlab.io/ctf/utctf-2020-crypto/
def bytes_to_polynomial(block, a): # block and element of field
    poly = 0
    bits = bin(bytes_to_long(block))[2:].zfill(128)
    for i in range(128):
        poly += a^i * int(bits[i])
    return poly

# I did change this one
def polynomial_to_bytes(poly):
    value = int(poly._integer_representation())
    out = 0
    for i in range(128):
        if (value >> i) & 1:
            out |= (1 << (127 - i))
    return out.to_bytes(16, "big")

def convert_to_blocks(ciphertext):
    blocks = [ciphertext[i:i + 16] for i in range(0, len(ciphertext), 16)]
    # this last-block padding was breaking it
    if blocks and len(blocks[-1]) < 16:
        blocks[-1] = blocks[-1].ljust(16, b"\x00")
    return blocks

# set up the field. This defines a base field, then uses that for the modulus polynomial of GF(2^128)
F.<a> = GF(2)[]
F.<x> = GF(2^128, modulus=a^128 + a^7 + a^2 + a + 1)

# then we make a polynomial in that ring
R.<H> = PolynomialRing(F)

# you can then use .roots() to find the candidate values for H

# URL = "http://localhost:8081"
URL = "https://aes.csa.cyberjousting.com/"

def decrypt(nonce, ciphertext, tag):
    # rebuild the cookie
    cookie_data = nonce + ciphertext + tag
    cookie_b64 = base64.urlsafe_b64encode(cookie_data).decode()

    response = requests.get(URL, cookies={"session": cookie_b64}).text
    if 'byuctf' in response:
        print("Found the flag: " + response)
    else:
        print("Decryption failed")

def encrypt():
    response = requests.post(f"{URL}/api/login", data={"username": "test", "password": "test"}, allow_redirects=False)

    # the cookie is formatted weird because of the choice in rust
    cookie = response.cookies.get("session")
    result = base64.urlsafe_b64decode(cookie)

    response2 = requests.get(URL, cookies={"session": response.cookies.get("session")})
    uuid = response2.headers.get("X-User-ID")
    return result[:12], result[12:-16], result[-16:], uuid

n0, c0, t0, uuid1 = encrypt()
n1, c1, t1, uuid2 = encrypt()
p0 = f"{{\"id\":\"{uuid1}\",\"role\":\"user\",\"username\":\"test\"}}".encode()

assert len(p0) == len(c0), "Plaintext and ciphertext should be the same length"
assert n0 == n1, "Nonces should be the same for this attack to work"

# L is big endian of the 2 bit-lengths
L = struct.pack('>QQ', 0, len(c0) * 8)

# first, split up a0 as needed, then split up c0 as needed
# into blocks, then into a polynomial for multiplication
C0 = convert_to_blocks(c0)
C1 = convert_to_blocks(c1)
c0_p = [bytes_to_polynomial(blk, x) for blk in C0]
c1_p = [bytes_to_polynomial(blk, x) for blk in C1]

# a0_p = bytes_to_polynomial(a0, x)
# a1_p = bytes_to_polynomial(a1, x)

t0_p = bytes_to_polynomial(t0, x)
t1_p = bytes_to_polynomial(t1, x)

L_p = bytes_to_polynomial(L, x)

p2 = f"{{\"id\":\"{uuid1}\",\"role\":\"admin\",\"username\":\"tes\"}}".encode()
c2 = xor(xor(c0, p0), p2)
C2 = convert_to_blocks(c2)
c2_p = [bytes_to_polynomial(blk, x) for blk in C2]

print("Made it to down here")


# # this ciphertext is 5 blocks long
# enc0_p = (c0_p[0] * H^6) + (c0_p[1] * H^5) + (c0_p[2] * H^4) + (c0_p[3] * H^3) + (c0_p[4] * H^2) + (L_p * H) + t0_p
# enc1_p = (c1_p[0] * H^6) + (c1_p[1] * H^5) + (c1_p[2] * H^4) + (c1_p[3] * H^3) + (c1_p[4] * H^2) + (L_p * H) + t1_p
# enc2_p = (c2_p[0] * H^6) + (c2_p[1] * H^5) + (c2_p[2] * H^4) + (c2_p[3] * H^3) + (c2_p[4] * H^2) + (L_p * H) # tag added later

# enc1_p_chk = (c1_p[0] * H^6) + (c1_p[1] * H^5) + (c1_p[2] * H^4) + (c1_p[3] * H^3) + (c1_p[4] * H^2) + (L_p * H)

def ghash_poly(block_polys, tag_poly=None):
    n = len(block_polys)
    result = 0
    for i, block_poly in enumerate(block_polys):
        result += block_poly * (H^(n + 1 - i))
    result += L_p * H
    if tag_poly is not None:
        result += tag_poly
    return result

enc0_p = ghash_poly(c0_p, t0_p)
enc1_p = ghash_poly(c1_p, t1_p)
enc2_p = ghash_poly(c2_p)
enc1_p_chk = ghash_poly(c1_p)

print("Constructed polynomials...")

masked = enc0_p + enc1_p
for h, _ in masked.roots():
    S = enc0_p(h)
    # test it first
    t3 = enc1_p_chk(h) + S
    t2 = enc2_p(h) + S # masked tag for forged CT
    bytes_t2 = polynomial_to_bytes(t2)
    print("H: " + str(h) + "\tT3: " + str(bytes_t2.hex()))
    decrypt(n0, c2, bytes_t2)

# # now we attempt the re-encryption

# example_uuid = '{"id":"550e8400-e29b-41d4-a716-446655440000","role":"user","username":"test"}'
